CREATE SCHEMA Hilos
GO

USE Hilos
GO

IF NOT EXISTS (
    SELECT name
        FROM sys.databases
        WHERE name = 'Hilos'
)
CREATE DATABASE Hilos
GO

USE Hilos
GO
-- para ver las tablas pero hay que seleccionar el schema
-- SELECT * from sysobjects where type ='U'

    CREATE TABLE Hilos.PRODUCTO(
        ID INT PRIMARY KEY IDENTITY,
        NOMBREPRODUCTO VARCHAR(25),
        PRECIO MONEY,
        DESCRIPCION VARCHAR(500),
        IDCATEGORIA INT,
        IDPROVEEDOR INT
    );

    CREATE TABLE Hilos.CATEGORIA(
        ID INT PRIMARY KEY IDENTITY,
        CATEGORIA VARCHAR(100)
    );

    CREATE TABLE Hilos.PERSONA(
        ID INT PRIMARY KEY IDENTITY,
        DPI VARCHAR(25) NOT NULL,
        PNOMBRE VARCHAR(50) NOT NULL,
        SNOMBRE VARCHAR(50),
        TNOMBRE VARCHAR(50),
        PAPELLIDO VARCHAR(50),
        SAPELLIDO VARCHAR(50),
        CAPELLIDO VARCHAR(50),
        NIT VARCHAR(14),
        NACIONALIDAD VARCHAR(50),
        IDTELEFONO INT,
        IDDIRECCION INT
    );


    CREATE TABLE Hilos.TELEFONO(
        ID INT PRIMARY KEY IDENTITY,
        PAIS VARCHAR(5),
        TELEFONO VARCHAR(15)
    );

    CREATE TABLE Hilos.DIRECCION(
        ID INT PRIMARY KEY IDENTITY,
        CASA VARCHAR(5),
        CALLE VARCHAR(50),
        AVENIDA VARCHAR(50),
        COLONIA VARCHAR(50),
        PUEBLO VARCHAR(50),
        DEPARTAMENTO VARCHAR(50),
        PAIS VARCHAR(50)
    );

    CREATE TABLE Hilos.USUARIO(
        ID INT PRIMARY KEY IDENTITY,
        USUARIO VARCHAR(50) NOT NULL,
        CONTRASENA VARCHAR(150) NOT NULL,
        IDPERSONA INT,
        IDROL INT
    );

    CREATE TABLE Hilos.PROVEEDOR(
        ID INT PRIMARY KEY IDENTITY,
        SOCIEDAD VARCHAR(255),
        COMERCIAL VARCHAR(255),
        NIT VARCHAR(14),
        IDDIRECCION INT,
        IDTELEFONO INT
    );

    CREATE TABLE Hilos.CLIENTE(
        ID INT PRIMARY KEY IDENTITY,
        NOMBRES VARCHAR(150),
        APELLIDOS VARCHAR(150),
        NIT VARCHAR(14),
        IDDIRECCION INT
    );

    CREATE TABLE Hilos.ROLES(
        ID INT PRIMARY KEY IDENTITY,
        ROL VARCHAR(50),
    );

    CREATE TABLE Hilos.FACTURA(
        ID INT PRIMARY KEY IDENTITY,
        IDCLIENTE INT,
        IDDETALLEFACTURA INT,
        TOTAL MONEY
    );

    CREATE TABLE Hilos.DETALLEFACTURA(
        ID INT PRIMARY KEY IDENTITY,
        IDPRODUCTO INT,
        CANTIDAD INT,
        SUBTOTAL MONEY
    );

   
    insert into Hilos.ROLES values('ADMINISTRADOR');
    INSERT INTO Hilos.ROLES values('OPERADOR');

    